import { useRef } from 'react'
import { Download, Share2 } from 'lucide-react'

interface Participant {
  id: number
  name: string
  custom: string
}

interface SplitReceiptProps {
  total: string
  grandTotal: number
  participants: Participant[]
  splitMode: string
  perPerson: number
  tip: string
  tipAmount: number
}

export default function SplitReceipt({ total, grandTotal, participants, splitMode, perPerson, tip, tipAmount }: SplitReceiptProps) {
  const receiptRef = useRef<HTMLDivElement>(null)

  const downloadReceipt = async () => {
    const { default: html2canvas } = await import('html2canvas')
    if (!receiptRef.current) return
    const canvas = await html2canvas(receiptRef.current, { scale: 2, backgroundColor: '#ffffff' })
    const a = document.createElement('a')
    a.download = `splitpay-receipt-${Date.now()}.png`
    a.href = canvas.toDataURL('image/png')
    a.click()
  }

  const shareReceipt = async () => {
    const { default: html2canvas } = await import('html2canvas')
    if (!receiptRef.current) return
    const canvas = await html2canvas(receiptRef.current, { scale: 2, backgroundColor: '#ffffff' })
    canvas.toBlob(async (blob) => {
      if (!blob) return
      const file = new File([blob], 'splitpay-receipt.png', { type: 'image/png' })
      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: 'SplitPay Receipt' })
      } else {
        downloadReceipt()
      }
    })
  }

  const date = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })

  return (
    <div className="mt-4">
      {/* Receipt Preview */}
      <div ref={receiptRef} className="bg-white p-6 rounded-2xl border border-gray-100 font-mono">
        {/* Header */}
        <div className="text-center mb-4 border-b border-dashed border-gray-300 pb-4">
          <h2 className="text-xl font-bold text-gray-900">SPLITPAY</h2>
          <p className="text-xs text-gray-400">Digital Receipt</p>
          <p className="text-xs text-gray-400 mt-1">{date}</p>
        </div>

        {/* Bill Details */}
        <div className="space-y-1 mb-4 text-sm">
          <div className="flex justify-between">
            <span className="text-gray-500">Bill Amount</span>
            <span className="text-gray-800">Rs.{parseFloat(total || '0').toFixed(2)}</span>
          </div>
          {parseFloat(tip) > 0 && (
            <div className="flex justify-between">
              <span className="text-gray-500">Tip ({tip}%)</span>
              <span className="text-gray-800">Rs.{tipAmount.toFixed(2)}</span>
            </div>
          )}
          <div className="flex justify-between font-bold border-t border-dashed border-gray-300 pt-2 mt-2">
            <span>Total</span>
            <span>Rs.{grandTotal.toFixed(2)}</span>
          </div>
        </div>

        {/* Participants */}
        <div className="border-t border-dashed border-gray-300 pt-4 mb-4">
          <p className="text-xs text-gray-400 mb-3 uppercase tracking-widest">Split Details</p>
          <div className="space-y-2">
            {participants.map((p, i) => {
              const amount = splitMode === 'equal'
                ? perPerson.toFixed(2)
                : parseFloat(p.custom || '0').toFixed(2)
              return (
                <div key={p.id} className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 bg-violet-100 rounded-full flex items-center justify-center text-violet-600 text-xs font-bold">{i + 1}</div>
                    <span className="text-sm text-gray-800">{p.name || `Person ${i + 1}`}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-gray-900">Rs.{amount}</span>
                    <span className="text-xs bg-green-100 text-green-600 px-2 py-0.5 rounded-full">PAID</span>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="text-center border-t border-dashed border-gray-300 pt-4">
          <p className="text-xs text-gray-400">Generated by SplitPay</p>
          <p className="text-xs text-violet-500 mt-1">splitpay-five.vercel.app</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3 mt-3">
        <button onClick={downloadReceipt} className="flex-1 flex items-center justify-center gap-2 border border-gray-200 text-gray-600 rounded-xl py-3 text-sm font-medium">
          <Download size={16} /> Download
        </button>
        <button onClick={shareReceipt} className="flex-1 flex items-center justify-center gap-2 bg-violet-600 text-white rounded-xl py-3 text-sm font-medium">
          <Share2 size={16} /> Share Receipt
        </button>
      </div>
    </div>
  )
}