import jsPDF from 'jspdf'

interface Participant {
  id: number
  name: string
  custom: string
}

interface ExportData {
  total: string
  tip: string
  tipAmount: number
  grandTotal: number
  splitMode: string
  perPerson: number
  participants: Participant[]
  note?: string
}

export function exportSplitPDF(data: ExportData) {
  const doc = new jsPDF()

  doc.setFontSize(22)
  doc.setTextColor(109, 40, 217)
  doc.text('SplitPay', 20, 20)

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text('Split Summary', 20, 30)
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 20, 38)

  if (data.note) {
    doc.text(`Note: ${data.note}`, 20, 46)
  }

  doc.setDrawColor(200, 200, 200)
  doc.line(20, 52, 190, 52)

  doc.setFontSize(11)
  doc.setTextColor(0, 0, 0)
  doc.text(`Total Bill:`, 20, 62)
  doc.text(`Rs. ${data.total}`, 150, 62)

  if (parseFloat(data.tip) > 0) {
    doc.text(`Tip (${data.tip}%):`, 20, 70)
    doc.text(`Rs. ${data.tipAmount.toFixed(2)}`, 150, 70)
  }

  doc.setFontSize(13)
  doc.setTextColor(109, 40, 217)
  doc.text(`Grand Total:`, 20, 82)
  doc.text(`Rs. ${data.grandTotal.toFixed(2)}`, 150, 82)

  doc.setDrawColor(200, 200, 200)
  doc.line(20, 88, 190, 88)

  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text('Participants:', 20, 98)

  let y = 108
  data.participants.forEach((p, i) => {
    const amount = data.splitMode === 'equal'
      ? data.perPerson.toFixed(2)
      : parseFloat(p.custom || '0').toFixed(2)
    doc.setFontSize(11)
    doc.setTextColor(50, 50, 50)
    doc.text(`${i + 1}. ${p.name || 'Person ' + (i + 1)}`, 25, y)
    doc.text(`Rs. ${amount}`, 150, y)
    y += 10
  })

  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by SplitPay', 20, 280)

  doc.save(`splitpay-${Date.now()}.pdf`)
}